[phases.setup]
nixPkgs = ["pnpm"]
commands = ["corepack enable", "corepack prepare pnpm@latest --activate"]

[phases.install]
cmd = "pnpm install"

[phases.build]
cmd = "pnpm run build"

[phases.start]
cmd = "pnpm start"

[settings]
skip_caddy = true
