export const discWordGroups: { id: string; words: [string, string, string, string] }[] = [
  { id: 'd1', words: ['Decidido', 'Entusiasta', 'Paciente', 'Preciso'] },
  { id: 'd2', words: ['Firme', 'Sociable', 'Leal', 'Analítico'] },
  { id: 'd3', words: ['Directo', 'Persuasivo', 'Estable', 'Sistemático'] },
  { id: 'd4', words: ['Competitivo', 'Optimista', 'Predecible', 'Cuidadoso'] },
  { id: 'd5', words: ['Audaz', 'Expresivo', 'Relajado', 'Consistente'] },
  { id: 'd6', words: ['Enérgico', 'Inspirador', 'Comprensivo', 'Formal'] },
  { id: 'd7', words: ['Independiente', 'Comunicativo', 'Diplomático', 'Ordenado'] },
  { id: 'd8', words: ['Resuelto', 'Convincente', 'Moderado', 'Minucioso'] },
  { id: 'd9', words: ['Osado', 'Afectuoso', 'Humilde', 'Detallista'] },
  { id: 'd10', words: ['Exigente', 'Gregario', 'Tolerante', 'Disciplinado'] },
  { id: 'd11', words: ['Tenaz', 'Cálido', 'Sosegado', 'Perfeccionista'] },
  { id: 'd12', words: ['Dominante', 'Entusiasta', 'Leal', 'Cauteloso'] },
];

export const wonderlicQuestions = [
  { id: 1, type: 'logic' as const, question: '¿Qué número continúa la serie? 2, 6, 18, 54, ___', options: ['108', '162', '72', '90'], correct: 1 },
  { id: 2, type: 'verbal' as const, question: '¿Cuál es la palabra que NO pertenece al grupo?', options: ['Martillo', 'Sierra', 'Taladro', 'Clavo'], correct: 3 },
  { id: 3, type: 'math' as const, question: 'Si 3 operarios tardan 8 horas en construir un muro, ¿cuántas horas tardarán 6 operarios?', options: ['4', '6', '16', '2'], correct: 0 },
  { id: 4, type: 'logic' as const, question: '¿Qué figura completa la secuencia? Triángulo → Cuadrado → Pentágono → ___', options: ['Hexágono', 'Círculo', 'Rectángulo', 'Trapecio'], correct: 0 },
  { id: 5, type: 'verbal' as const, question: 'La palabra "mineral" está a "roca" como "agua" está a: ___', options: ['Río', 'Océano', 'Lluvia', 'Hielo'], correct: 2 },
  { id: 6, type: 'math' as const, question: 'Una pala cargadora mueve 12 toneladas por ciclo. Si cada ciclo toma 4 minutos, ¿cuántas toneladas moverá en 1 hora?', options: ['144', '180', '120', '168'], correct: 1 },
  { id: 7, type: 'logic' as const, question: 'María es mayor que Juan. Pedro es menor que María. Juan es mayor que Pedro. ¿Quién es el menor?', options: ['María', 'Juan', 'Pedro', 'No se puede determinar'], correct: 2 },
  { id: 8, type: 'verbal' as const, question: '¿Qué par de palabras tienen una relación más cercana?', options: ['Seguridad-Casco', 'Mineral-Yacimiento', 'Perforación-Explosión', 'Supervisor-Turno'], correct: 1 },
  { id: 9, type: 'math' as const, question: 'Un camión minero viaja a 45 km/h. ¿Cuántos kilómetros recorre en 2 horas y 20 minutos?', options: ['90', '105', '100', '115'], correct: 1 },
  { id: 10, type: 'logic' as const, question: 'Si todos los supervisores son ingenieros y algunos ingenieros trabajan en mina, ¿es cierto que algunos supervisores trabajan en mina?', options: ['Sí, siempre', 'No, nunca', 'No necesariamente', 'Solo si son geólogos'], correct: 2 },
  { id: 11, type: 'verbal' as const, question: 'Elija el sinónimo de "idóneo":', options: ['Adecuado', 'Inhábil', 'Dudoso', 'Temporal'], correct: 0 },
  { id: 12, type: 'math' as const, question: 'Si 5 litros de agua pesan 5 kg, ¿cuánto pesan 3.5 litros?', options: ['3.5 kg', '4 kg', '3 kg', '2.5 kg'], correct: 0 },
  { id: 13, type: 'logic' as const, question: '¿Qué número continúa? 1, 1, 2, 3, 5, 8, ___', options: ['10', '13', '12', '11'], correct: 1 },
  { id: 14, type: 'verbal' as const, question: 'Complete la analogía: Perforación : Broca :: Corte : ___', options: ['Sierra', 'Martillo', 'Cincel', 'Láser'], correct: 2 },
  { id: 15, type: 'logic' as const, question: 'En una fila de 8 personas, Carlos está en la posición 3. ¿Cuántas personas están detrás de él?', options: ['4', '5', '6', '3'], correct: 1 },
  { id: 16, type: 'math' as const, question: 'Un contratista ofrece S/ 240 por 6 horas de trabajo. ¿Cuánto pagará por 15 horas al mismo ritmo?', options: ['S/ 600', 'S/ 540', 'S/ 480', 'S/ 660'], correct: 0 },
  { id: 17, type: 'logic' as const, question: '¿Cuál de las siguientes afirmaciones es una inferencia lógica? "Todos los mineros usan casco. Juan es minero."', options: ['Juan usa casco', 'Juan no usa casco', 'Algunos mineros no usan casco', 'El casco es naranja'], correct: 0 },
  { id: 18, type: 'verbal' as const, question: 'Seleccione el antónimo de "obsoleto":', options: ['Moderno', 'Dañado', 'Antiguo', 'Lento'], correct: 0 },
  { id: 19, type: 'math' as const, question: 'La producción de una mina aumentó un 15% en enero y luego un 10% en febrero. Si la producción inicial era 2000 ton/día, ¿cuál es la producción actual?', options: ['2500', '2530', '2480', '2600'], correct: 1 },
  { id: 20, type: 'logic' as const, question: 'Ana, Beto y Carla tienen diferentes cargos: Geólogo, Supervisor, HSE. Ana no es Geólogo. Beto no es HSE. Carla no es Supervisor. ¿Quién es HSE?', options: ['Ana', 'Beto', 'Carla', 'No se sabe'], correct: 0 },
  { id: 21, type: 'verbal' as const, question: '¿Qué palabra completa mejor la oración? "El ingeniero _____ los planos antes de la reunión."', options: ['revisó', 'revisaba', 'revisará', 'revisaría'], correct: 0 },
  { id: 22, type: 'math' as const, question: 'Si una bomba extrae 150 litros/minuto, ¿cuántos litros extraerá en 3 horas y media?', options: ['31,500', '27,000', '30,000', '28,500'], correct: 0 },
  { id: 23, type: 'logic' as const, question: '¿Cuál es el próximo elemento en la secuencia? A, C, F, J, ___', options: ['O', 'N', 'M', 'P'], correct: 1 },
  { id: 24, type: 'verbal' as const, question: '¿Cuál de estas palabras está mal escrita?', options: ['Excavación', 'Perforación', 'Administración', 'Mantenimiento'], correct: 3 },
  { id: 25, type: 'logic' as const, question: 'Un rectángulo tiene 24 cm de perímetro. Si su largo es el doble de su ancho, ¿cuánto mide el ancho?', options: ['4 cm', '6 cm', '8 cm', '3 cm'], correct: 0 },
  { id: 26, type: 'math' as const, question: 'Se extrajeron 480 kg de mineral. Si la ley es 2.5%, ¿cuántos kg de metal puro se obtienen?', options: ['10 kg', '12 kg', '8 kg', '15 kg'], correct: 1 },
  { id: 27, type: 'logic' as const, question: 'Si ayer fuese mañana, hoy sería viernes. ¿Qué día es hoy?', options: ['Domingo', 'Jueves', 'Miércoles', 'Sábado'], correct: 0 },
  { id: 28, type: 'verbal' as const, question: 'Seleccione la palabra que significa "persona que supervisa una operación":', options: ['Subordinado', 'Superintendente', 'Operario', 'Asistente'], correct: 1 },
  { id: 29, type: 'math' as const, question: 'Un valor se deprecia 20% anual. Si hoy vale S/ 50,000, ¿cuánto valdrá en 2 años?', options: ['S/ 32,000', 'S/ 30,000', 'S/ 28,000', 'S/ 35,000'], correct: 0 },
  { id: 30, type: 'logic' as const, question: 'Complete: 1/4 es a 0.25 como 1/8 es a ___', options: ['0.125', '0.25', '0.5', '0.0625'], correct: 0 },
];

export const bigFiveQuestions = [
  { id: 1, text: 'Trabajo de manera organizada y planificada.', dimension: 'conscientiousness' as const, direction: 'positive' as const },
  { id: 2, text: 'Me siento tranquilo/a en situaciones de presión.', dimension: 'neuroticism' as const, direction: 'negative' as const },
  { id: 3, text: 'Disfruto trabajar en equipo con otros compañeros.', dimension: 'extraversion' as const, direction: 'positive' as const },
  { id: 4, text: 'Estoy abierto/a a nuevas ideas y formas de trabajo.', dimension: 'openness' as const, direction: 'positive' as const },
  { id: 5, text: 'Confío en las intenciones de mis compañeros.', dimension: 'agreeableness' as const, direction: 'positive' as const },
  { id: 6, text: 'Completo todas mis tareas antes de los plazos establecidos.', dimension: 'conscientiousness' as const, direction: 'positive' as const },
  { id: 7, text: 'Me estreso fácilmente cuando algo sale mal.', dimension: 'neuroticism' as const, direction: 'positive' as const },
  { id: 8, text: 'Soy una persona que habla poco en reuniones.', dimension: 'extraversion' as const, direction: 'negative' as const },
  { id: 9, text: 'Me interesa aprender nuevas tecnologías mineras.', dimension: 'openness' as const, direction: 'positive' as const },
  { id: 10, text: 'Soy comprensivo/a con los errores de los demás.', dimension: 'agreeableness' as const, direction: 'positive' as const },
  { id: 11, text: 'Soy meticuloso/a en la revisión de mi trabajo.', dimension: 'conscientiousness' as const, direction: 'positive' as const },
  { id: 12, text: 'Mis emociones cambian rápidamente durante el día.', dimension: 'neuroticism' as const, direction: 'positive' as const },
  { id: 13, text: 'Me gusta ser el centro de atención en el grupo.', dimension: 'extraversion' as const, direction: 'positive' as const },
  { id: 14, text: 'Prefiero rutinas establecidas que cambios constantes.', dimension: 'openness' as const, direction: 'negative' as const },
  { id: 15, text: 'Colaboro activamente con mis compañeros sin que me lo pidan.', dimension: 'agreeableness' as const, direction: 'positive' as const },
  { id: 16, text: 'Mantengo mi área de trabajo limpia y ordenada.', dimension: 'conscientiousness' as const, direction: 'positive' as const },
  { id: 17, text: 'Me preocupo demasiado por la calidad de mi trabajo.', dimension: 'neuroticism' as const, direction: 'positive' as const },
  { id: 18, text: 'Disfruto conocer personas nuevas en el trabajo.', dimension: 'extraversion' as const, direction: 'positive' as const },
  { id: 19, text: 'Me adapto fácilmente a nuevos procedimientos.', dimension: 'openness' as const, direction: 'positive' as const },
  { id: 20, text: 'Evito conflictos innecesarios con mis colegas.', dimension: 'agreeableness' as const, direction: 'positive' as const },
  { id: 21, text: 'Verifico dos veces mi trabajo antes de darlo por terminado.', dimension: 'conscientiousness' as const, direction: 'positive' as const },
  { id: 22, text: 'Duermo bien incluso antes de un día importante.', dimension: 'neuroticism' as const, direction: 'negative' as const },
  { id: 23, text: 'Prefiero trabajar solo/a que en equipo.', dimension: 'extraversion' as const, direction: 'negative' as const },
  { id: 24, text: 'Me gusta experimentar con nuevas herramientas.', dimension: 'openness' as const, direction: 'positive' as const },
  { id: 25, text: 'Defiendo a mis compañeros cuando son criticados.', dimension: 'agreeableness' as const, direction: 'positive' as const },
];

export const integrityQuestions = [
  { id: 1, text: 'Si encontrara un error en un reporte que me beneficia, lo reportaría aunque nadie lo haya notado.', category: 'honesty' as const },
  { id: 2, text: 'He tomado alguna vez materiales del trabajo para uso personal.', category: 'honesty' as const },
  { id: 3, text: 'Si un compañero comete un error de seguridad, debo reportarlo aunque sea mi amigo.', category: 'ethics' as const },
  { id: 4, text: 'En minería, a veces es necesario omitir ciertos protocolos para cumplir la producción.', category: 'risk' as const },
  { id: 5, text: 'Si viera a un supervisor manipulando un reporte de seguridad, lo denunciaría.', category: 'ethics' as const },
  { id: 6, text: 'Consumir alcohol después del turno es aceptable siempre que no afecte el siguiente.', category: 'risk' as const },
  { id: 7, text: 'He justificado alguna vez un retraso con una excusa no del todo cierta.', category: 'honesty' as const },
  { id: 8, text: 'Las normas de seguridad están para cumplirse siempre, sin excepción.', category: 'compliance' as const },
  { id: 9, text: 'Si un equipo tiene una falla menor, puedo seguir usándolo y reportarlo después.', category: 'risk' as const },
  { id: 10, text: 'Aceptaría un soborno si nadie se enterara y beneficiara a mi familia.', category: 'honesty' as const },
  { id: 11, text: 'Es aceptable "maquillar" cifras de producción si el resultado final es positivo.', category: 'ethics' as const },
  { id: 12, text: 'Reporto inmediatamente cualquier condición insegura que observo.', category: 'compliance' as const },
  { id: 13, text: 'A veces es necesario trabajar sin EPP completo si la tarea es corta.', category: 'risk' as const },
  { id: 14, text: 'He visto a compañeros incumplir normas y no he dicho nada.', category: 'ethics' as const },
  { id: 15, text: 'Mentiría en una prueba de alcohol si mi trabajo estuviera en riesgo.', category: 'honesty' as const },
  { id: 16, text: 'Debo cumplir las normas aunque retrasen mi trabajo.', category: 'compliance' as const },
  { id: 17, text: 'Tomar documentos técnicos confidenciales para compartirlos no es grave.', category: 'ethics' as const },
  { id: 18, text: 'Si un compañero opera bajo efectos del alcohol, debo reportarlo.', category: 'ethics' as const },
  { id: 19, text: 'Normalizar ciertos riesgos es parte de trabajar en mina.', category: 'risk' as const },
  { id: 20, text: 'La honestidad es el valor más importante en un equipo de trabajo.', category: 'compliance' as const },
];

export const hoganQuestions = [
  { id: 1, text: 'Prefiero tomar decisiones rápidas aunque no tenga toda la información.', dimension: 'leadership' as const },
  { id: 2, text: 'Siempre reviso mis acciones antes de actuar.', dimension: 'prudence' as const },
  { id: 3, text: 'Me recupero rápidamente después de un fracaso.', dimension: 'resilience' as const },
  { id: 4, text: 'Disfruto conocer a nuevas personas en el trabajo.', dimension: 'sociability' as const },
  { id: 5, text: 'Estoy siempre buscando nuevas formas de hacer mi trabajo.', dimension: 'learning' as const },
  { id: 6, text: 'Asumo la responsabilidad cuando las cosas salen mal.', dimension: 'leadership' as const },
  { id: 7, text: 'Planifico mis actividades con varios días de anticipación.', dimension: 'prudence' as const },
  { id: 8, text: 'Mantengo la calma cuando enfrento críticas.', dimension: 'resilience' as const },
  { id: 9, text: 'Me siento cómodo/a hablando en público.', dimension: 'sociability' as const },
  { id: 10, text: 'Aprendo rápidamente a usar nuevos equipos y software.', dimension: 'learning' as const },
  { id: 11, text: 'Puedo motivar a mi equipo incluso en situaciones difíciles.', dimension: 'leadership' as const },
  { id: 12, text: 'Soy cuidadoso/a con los recursos de la empresa.', dimension: 'prudence' as const },
  { id: 13, text: 'No me afectan los comentarios negativos sobre mi trabajo.', dimension: 'resilience' as const },
  { id: 14, text: 'Prefiero trabajar en equipo que solo/a.', dimension: 'sociability' as const },
  { id: 15, text: 'Leo regularmente manuales técnicos y actualizaciones.', dimension: 'learning' as const },
  { id: 16, text: 'Delego tareas efectivamente a mi equipo.', dimension: 'leadership' as const },
  { id: 17, text: 'Evito riesgos innecesarios en el trabajo.', dimension: 'prudence' as const },
  { id: 18, text: 'Puedo trabajar efectivamente bajo presión extrema.', dimension: 'resilience' as const },
  { id: 19, text: 'Establezco relaciones profesionales con facilidad.', dimension: 'sociability' as const },
  { id: 20, text: 'Busco activamente retroalimentación para mejorar.', dimension: 'learning' as const },
];

export const fitSocialQuestions = [
  { id: 1, text: 'Considero que el diálogo con las comunidades es tan importante como el avance técnico.', dimension: 'comunidad' as const, direction: 'positive' as const },
  { id: 2, text: 'Entiendo las tradiciones locales y valoro el uso de idiomas originarios (Quechua/Aimara) en la zona.', dimension: 'cultura' as const, direction: 'positive' as const },
  { id: 3, text: 'En una situación de conflicto social, la fuerza es el primer recurso para mantener la operación.', dimension: 'conflictos' as const, direction: 'negative' as const },
  { id: 4, text: 'Busco generar valor compartido entre la empresa y la población local en mis proyectos.', dimension: 'sostenibilidad' as const, direction: 'positive' as const },
  { id: 5, text: 'Me siento cómodo participando en asambleas comunales para explicar impactos técnicos.', dimension: 'comunidad' as const, direction: 'positive' as const },
  { id: 6, text: 'Creo que el desarrollo de la mina debe ser independiente del desarrollo del pueblo cercano.', dimension: 'sostenibilidad' as const, direction: 'negative' as const },
  { id: 7, text: 'Respeto los tiempos de las comunidades aunque esto retrase cronogramas técnicos.', dimension: 'conflictos' as const, direction: 'positive' as const },
  { id: 8, text: 'Tengo interés en aprender o mejorar mi nivel de Quechua para comunicarme mejor.', dimension: 'cultura' as const, direction: 'positive' as const },
  { id: 9, text: 'La licencia social es una responsabilidad de todos, no solo del área de RRCC.', dimension: 'comunidad' as const, direction: 'positive' as const },
  { id: 10, text: 'Ignorar las preocupaciones locales es aceptable si el proyecto tiene aprobación estatal.', dimension: 'conflictos' as const, direction: 'negative' as const },
];

export const moduleNames: Record<string, string> = {
  disc: 'Evaluación DISC',
  wonderlic: 'Test Wonderlic',
  bigfive: 'Inventario Big Five',
  integridad: 'Evaluación de Integridad',
  hogan: 'Hogan Assessment',
  fitsocial: 'Aptitud Social y Licencia Social',
};
